movie_library/routes.py
import functools
import uuid
from dataclasses import asdict
from flask import Blueprint, render_template, session, redirect, url_for, request, flash, current_app, abort
from flask_mail import Message
from itsdangerous import URLSafeTimedSerializer, SignatureExpired, BadSignature
from werkzeug.security import check_password_hash, generate_password_hash
from movie_library import mail, Config
from movie_library.forms import MovieForm, ExtendedMovieForm, RegisterForm, LoginForm
from movie_library.models import Movie, current_day, current_year, User

pages = Blueprint(
    "pages", __name__, template_folder="templates", static_folder="static"
)


# creating login required decorator
def login_required(route):
    @functools.wraps(route)
    def route_wrapper(*args, **kwargs):
        if not session.get("email"):
            return redirect(url_for(".login"))
        return route(*args, **kwargs)

    return route_wrapper


@pages.context_processor
def inject_current_year():
    return {"year": current_year}


# Serializer for token generation
serializer = URLSafeTimedSerializer(Config.SECRET_KEY)


@pages.route("/register", methods=["GET", "POST"])
def register():
    if session.get("email"):
        return redirect(url_for(".index"))

    form = RegisterForm()
    if form.validate_on_submit():
        # hash and salt password
        hash_and_salted_password = generate_password_hash(password=form.password.data, method="pbkdf2:sha256",
                                                          salt_length=8)
        new_user = User(
            _id=uuid.uuid4().hex,
            name=form.name.data,
            email=form.email.data,
            password=hash_and_salted_password,
        )

        # add new user to db
        current_app.db.users.insert_one(asdict(new_user))

        token = serializer.dumps(new_user.email, salt='email-confirm')

        # Send email confirmation to user
        confirmation_url = url_for('pages.confirm_email', token=token, _external=True)
        html = render_template('email_confirmation.html', user_name=new_user.name, confirmation_url=confirmation_url)
        msg = Message("Confirm Your Email Address", recipients=[new_user.email], html=html)
        mail.send(msg)

        flash(message=f"A confirmation email has been sent to {new_user.email}", category="success")
        return redirect(url_for(".register"))

    return render_template("register.html", form=form, title="Movies Watchlist - Register")


@pages.route('/confirm_email/<token>')
def confirm_email(token):
    """Returns the url that take the user to the login page to confirm his registration and update user confirm to
    True"""
    try:
        email = serializer.loads(token, salt='email-confirm', max_age=3600)
        requested_user = current_app.db.users.find_one({"email": email})
        if requested_user:
            requested_user["confirmed"] = True
            current_app.db.users.update_one({"email": email}, {"$set": {"confirmed": requested_user["confirmed"]}})
            flash(message="Your email address has been confirmed. Thank you for registering!", category="success")

        else:
            flash(message="There was an error confirming your email address. Please try again.", category="danger")
    except SignatureExpired:
        flash(message="The confirmation link has expired. Please request a new confirmation email.", category="danger")
    except BadSignature:
        flash(message="The confirmation link is invalid. Please request a new confirmation email.", category="danger")
    except Exception as e:
        flash(message="An error occurred while confirming your email address. Please try again later.",
              category="danger")
        print(e)  # print the error message for debugging purposes
    return redirect(url_for('.login'))


@pages.route("/login", methods=["GET", "POST"])
def login():
    if session.get("email"):
        return redirect(url_for(".index"))

    form = LoginForm()
    if form.validate_on_submit():
        user_data = current_app.db.users.find_one({"email": form.email.data})

        if not user_data:
            flash(message=f"That email does not exist, please try again.")
            return redirect(url_for('.login'))

        # Email exists and password correct
        elif user_data["confirmed"]:
            current_user = User(**user_data)
            hashed_password = current_user.password
            unhashed_password = form.password.data
            if check_password_hash(pwhash=hashed_password, password=unhashed_password):
                session["user_id"] = current_user.id
                session["email"] = current_user.email
                session["name"] = current_user.name
                # flash(message=f"You have been Successfully Logged in!", category="success")
                return redirect(url_for(".index"))

            # Password incorrect
            else:
                flash(message=f"You have entered a wrong password! Please try again!", category="danger")
                return redirect(url_for('.login'))

        # Check if the mail is not confirmed
        else:
            flash(message=f"Please confirm your email to log in!", category="danger")

    return render_template("login.html", form=form, title="Movies Watchlist - Login")


@pages.route("/logout")
def logout():
    # session.clear() : don't want reset dark mode to light ! want to keep session["theme"]
    del session["user_id"]
    del session["email"]
    del session["name"]
    return redirect(url_for(".login"))


@pages.route("/")
@login_required
def index():
    user_data = current_app.db.users.find_one({"email": session["email"]})
    current_user = User(**user_data)
    # display movies where their id is "in" user.movies list of ids
    all_movies = current_app.db.movie.find({"_id": {"$in": current_user.movies}})
    # print(all_movies)
    movies_list = [Movie(**movie_data) for movie_data in all_movies]
    # print("movies list", movies_list)
    return render_template("index.html", title="Movies Watchlist", movies_data=movies_list)


@pages.route('/add', methods=['GET', 'POST'])
@login_required
def add_movie():
    form = MovieForm()
    if form.validate_on_submit():
        flash("Movie added successfully.")

        new_movie = Movie(
            _id=uuid.uuid4().hex,
            title=form.title.data,
            director=form.director.data,
            year=form.year.data
        )
        # inject new movie to db
        current_app.db.movie.insert_one(asdict(new_movie))
        # add movie._id to the current user movies list
        current_app.db.users.update_one({"_id": session["user_id"]}, {"$push": {"movies": new_movie.id}})

        return redirect(url_for(".index"))

    return render_template("new_movie.html", form=form, title="Movies Watchlist - Add a Movie")


@pages.get("/movie/<string:_id>")
@login_required
def movie(_id: str):
    movie_data = current_app.db.movie.find_one({"_id": _id})
    # print("movie", movie_data)
    if not movie_data:
        abort(404)
    current_movie = Movie(**movie_data)
    # print("current_movie", current_movie)
    return render_template("movie_details.html", movie=current_movie, title="Movies Watchlist - Movie details")


@pages.route("/edit/<string:_id>", methods=["GET", "POST"])
@login_required
def edit_movie(_id: str):
    movie_to_edit = Movie(**current_app.db.movie.find_one({"_id": _id}))
    # render the fields with the existing data already from db
    form = ExtendedMovieForm(obj=movie_to_edit)
    # updating movie fields
    if form.validate_on_submit():
        movie_to_edit.cast = form.cast.data
        movie_to_edit.tags = form.tags.data
        movie_to_edit.series = form.series.data
        movie_to_edit.description = form.description.data
        movie_to_edit.video_link = form.video_link.data

        current_app.db.movie.update_one({"_id": _id},
                                        {"$set": asdict(movie_to_edit)})

        return redirect(url_for(".movie", _id=_id))

    return render_template("movie_form.html", form=form, movie=movie_to_edit)


@pages.get("/movie/<string:_id>/rate")
@login_required
def rate_movie(_id: str):
    rating = int(request.args.get("rating"))  # You must add rating value in jinja like _id
    current_app.db.movie.update_one({"_id": _id}, {"$set": {"rating": rating}})
    return redirect(url_for(".movie", _id=_id))


@pages.get("/movie/<string:_id>/watch")
@login_required
def watch_today(_id: str):
    current_app.db.movie.update_one({"_id": _id}, {"$set": {"last_watched": current_day}})
    return redirect(url_for(".movie", _id=_id))


@pages.get("/toggle-theme")
def toggle_theme():
    current_theme = session.get("theme")
    if current_theme == "dark":
        session["theme"] = "light"

    else:
        session["theme"] = "dark"

    return redirect(request.args.get("current_page"))

movie_library/templates/macros/fields.html
{% macro render_text_field(field) %}
<div class="form__group">
    {{ field.label(class_="form__label") }}
    {{ field(class_="form__field")}}

    {%- for error in field.errors %}
        <span class="form__error">{{ error }}</span>
    {% endfor %}

</div>
{% endmacro %}


{% macro render_area_field(field) %}
<div class="form__group">
    {{ field.label(class_="form__label") }}
    {{ field(rows=4, class_="form__field", style="resize: none") }}

    {%- for error in field.errors %}
        <span class="form__error">{{ error }}</span>
    {% endfor %}
</div>
{% endmacro %}

movie_library/templates/macros/footer.html
{% macro footer(year) %}
<footer class="footer">
    <small>Copyright &copy;{{ year }}. Movies Watchlist. All rights reserved.</small>
</footer>
{% endmacro %}

movie_library/templates/macros/nav.html
{% from "macros/svgs.html" import moon, sun %}
{% macro header(email, theme, name) %}

<header class="header">
    <div class="nav-container">
        <a href="{{ url_for('pages.index') }}" class="header__logo">
            <svg xmlns="http://www.w3.org/2000/svg" class="logo__icon" fill="none" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 4v16M17 4v16M3 8h4m10 0h4M3 12h18M3 16h4m10 0h4M4 20h16a1 1 0 001-1V5a1 1 0 00-1-1H4a1 1 0 00-1 1v14a1 1 0 001 1z" />
</svg> <span class="logo__name">Watchlist</span>
        </a>
        <nav class="nav">
            {%- if not email %}
                <a
                    href="{{ url_for('pages.login') }}"
                    class="nav__link {{ 'nav__link--active' if request.path == url_for('pages.login') }}"
                >
                    <span class="nav__item">Log in</span>
                </a>
                <a
                    href="{{ url_for('pages.register') }}"
                    class="nav__link {{ 'nav__link--active' if request.path == url_for('pages.register') }}"
                >
                    <span class="nav__item">Register</span>
                </a>
            {% else %}
                <a 
                    href="{{ url_for('pages.index') }}"
                    class="nav__link {{ 'nav__link--active' if request.path == url_for('pages.index') }}"
                >
                    <span class="nav__item">Movies</span>
                </a>
                <a
                    href="{{ url_for('pages.logout') }}"
                    class="nav__link"
                >
                    <span class="nav__item">Log out</span>
                </a>

                <a
                    href="#"
                    class="nav__link"
                >
                    <span class="nav__item">{{ name }}</span>
                </a>
            {% endif %}
            <a href="{{ url_for('pages.toggle_theme', current_page=request.path) }}" class="nav__link">
                <span class="nav__item">
                    {% if theme == "dark" %}
                        {{ sun("nav__icon") }}
                    {% else %}
                        {{ moon("nav__icon") }}
                    {% endif %}
                </span>
            </a>
        </nav>
    </div>
</header>
{% endmacro %}

movie_library/templates/macros/svgs.html
<!--bootstrap svg icons-->
{% macro star(class_) %}
<svg xmlns="http://www.w3.org/2000/svg" class="{{ class_ }}" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
</svg>
{% endmacro %}

{% macro pencil(class_) %}
<svg xmlns="http://www.w3.org/2000/svg" class="{{ class_ }}" fill="none" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
</svg>
{% endmacro %}

{% macro moon(class_) %}
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-moon-stars-fill {{ class_ }}" viewBox="0 0 16 16">
  <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
  <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
</svg>
{% endmacro %}

{% macro sun(class_) %}
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-sun-fill {{ class_ }}" viewBox="0 0 16 16">
  <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
</svg>
{% endmacro %}