movie_library/routes.py
import functools
import uuid
from dataclasses import asdict
from flask import Blueprint, render_template, session, redirect, url_for, request, flash, current_app, abort
from flask_mail import Message
from itsdangerous import URLSafeTimedSerializer, SignatureExpired, BadSignature
from werkzeug.security import check_password_hash, generate_password_hash
from movie_library import mail, Config
from movie_library.forms import MovieForm, ExtendedMovieForm, RegisterForm, LoginForm
from movie_library.models import Movie, current_day, current_year, User

pages = Blueprint(
    "pages", __name__, template_folder="templates", static_folder="static"
)


# creating login required decorator
def login_required(route):
    @functools.wraps(route)
    def route_wrapper(*args, **kwargs):
        if not session.get("email"):
            return redirect(url_for(".login"))
        return route(*args, **kwargs)

    return route_wrapper


@pages.context_processor
def inject_current_year():
    return {"year": current_year}


# Serializer for token generation
serializer = URLSafeTimedSerializer(Config.SECRET_KEY)


@pages.route("/register", methods=["GET", "POST"])
def register():
    if session.get("email"):
        return redirect(url_for(".index"))

    form = RegisterForm()
    if form.validate_on_submit():
        # hash and salt password
        hash_and_salted_password = generate_password_hash(password=form.password.data, method="pbkdf2:sha256",
                                                          salt_length=8)
        new_user = User(
            _id=uuid.uuid4().hex,
            name=form.name.data,
            email=form.email.data,
            password=hash_and_salted_password,
        )

        # add new user to db
        current_app.db.users.insert_one(asdict(new_user))

        token = serializer.dumps(new_user.email, salt='email-confirm')

        # Send email confirmation to user
        confirmation_url = url_for('pages.confirm_email', token=token, _external=True)
        html = render_template('email_confirmation.html', user_name=new_user.name, confirmation_url=confirmation_url)
        msg = Message("Confirm Your Email Address", recipients=[new_user.email], html=html)
        mail.send(msg)

        flash(message=f"A confirmation email has been sent to {new_user.email}", category="success")
        return redirect(url_for(".register"))

    return render_template("register.html", form=form, title="Movies Watchlist - Register")


@pages.route('/confirm_email/<token>')
def confirm_email(token):
    """Returns the url that take the user to the login page to confirm his registration and update user confirm to
    True"""
    try:
        email = serializer.loads(token, salt='email-confirm', max_age=3600)
        requested_user = current_app.db.users.find_one({"email": email})
        if requested_user:
            requested_user["confirmed"] = True
            current_app.db.users.update_one({"email": email}, {"$set": {"confirmed": requested_user["confirmed"]}})
            flash(message="Your email address has been confirmed. Thank you for registering!", category="success")

        else:
            flash(message="There was an error confirming your email address. Please try again.", category="danger")
    except SignatureExpired:
        flash(message="The confirmation link has expired. Please request a new confirmation email.", category="danger")
    except BadSignature:
        flash(message="The confirmation link is invalid. Please request a new confirmation email.", category="danger")
    except Exception as e:
        flash(message="An error occurred while confirming your email address. Please try again later.",
              category="danger")
        print(e)  # print the error message for debugging purposes
    return redirect(url_for('.login'))


@pages.route("/login", methods=["GET", "POST"])
def login():
    if session.get("email"):
        return redirect(url_for(".index"))

    form = LoginForm()
    if form.validate_on_submit():
        user_data = current_app.db.users.find_one({"email": form.email.data})

        if not user_data:
            flash(message=f"That email does not exist, please try again.")
            return redirect(url_for('.login'))

        # Email exists and password correct
        elif user_data["confirmed"]:
            current_user = User(**user_data)
            hashed_password = current_user.password
            unhashed_password = form.password.data
            if check_password_hash(pwhash=hashed_password, password=unhashed_password):
                session["user_id"] = current_user.id
                session["email"] = current_user.email
                session["name"] = current_user.name
                # flash(message=f"You have been Successfully Logged in!", category="success")
                return redirect(url_for(".index"))

            # Password incorrect
            else:
                flash(message=f"You have entered a wrong password! Please try again!", category="danger")
                return redirect(url_for('.login'))

        # Check if the mail is not confirmed
        else:
            flash(message=f"Please confirm your email to log in!", category="danger")

    return render_template("login.html", form=form, title="Movies Watchlist - Login")


@pages.route("/logout")
def logout():
    # session.clear() : don't want reset dark mode to light ! want to keep session["theme"]
    del session["user_id"]
    del session["email"]
    del session["name"]
    return redirect(url_for(".login"))


@pages.route("/")
@login_required
def index():
    user_data = current_app.db.users.find_one({"email": session["email"]})
    current_user = User(**user_data)
    # display movies where their id is "in" user.movies list of ids
    all_movies = current_app.db.movie.find({"_id": {"$in": current_user.movies}})
    # print(all_movies)
    movies_list = [Movie(**movie_data) for movie_data in all_movies]
    # print("movies list", movies_list)
    return render_template("index.html", title="Movies Watchlist", movies_data=movies_list)


@pages.route('/add', methods=['GET', 'POST'])
@login_required
def add_movie():
    form = MovieForm()
    if form.validate_on_submit():
        flash("Movie added successfully.")

        new_movie = Movie(
            _id=uuid.uuid4().hex,
            title=form.title.data,
            director=form.director.data,
            year=form.year.data
        )
        # inject new movie to db
        current_app.db.movie.insert_one(asdict(new_movie))
        # add movie._id to the current user movies list
        current_app.db.users.update_one({"_id": session["user_id"]}, {"$push": {"movies": new_movie.id}})

        return redirect(url_for(".index"))

    return render_template("new_movie.html", form=form, title="Movies Watchlist - Add a Movie")


@pages.get("/movie/<string:_id>")
@login_required
def movie(_id: str):
    movie_data = current_app.db.movie.find_one({"_id": _id})
    # print("movie", movie_data)
    if not movie_data:
        abort(404)
    current_movie = Movie(**movie_data)
    # print("current_movie", current_movie)
    return render_template("movie_details.html", movie=current_movie, title="Movies Watchlist - Movie details")


@pages.route("/edit/<string:_id>", methods=["GET", "POST"])
@login_required
def edit_movie(_id: str):
    movie_to_edit = Movie(**current_app.db.movie.find_one({"_id": _id}))
    # render the fields with the existing data already from db
    form = ExtendedMovieForm(obj=movie_to_edit)
    # updating movie fields
    if form.validate_on_submit():
        movie_to_edit.cast = form.cast.data
        movie_to_edit.tags = form.tags.data
        movie_to_edit.series = form.series.data
        movie_to_edit.description = form.description.data
        movie_to_edit.video_link = form.video_link.data

        current_app.db.movie.update_one({"_id": _id},
                                        {"$set": asdict(movie_to_edit)})

        return redirect(url_for(".movie", _id=_id))

    return render_template("movie_form.html", form=form, movie=movie_to_edit)


@pages.get("/movie/<string:_id>/rate")
@login_required
def rate_movie(_id: str):
    rating = int(request.args.get("rating"))  # You must add rating value in jinja like _id
    current_app.db.movie.update_one({"_id": _id}, {"$set": {"rating": rating}})
    return redirect(url_for(".movie", _id=_id))


@pages.get("/movie/<string:_id>/watch")
@login_required
def watch_today(_id: str):
    current_app.db.movie.update_one({"_id": _id}, {"$set": {"last_watched": current_day}})
    return redirect(url_for(".movie", _id=_id))


@pages.get("/toggle-theme")
def toggle_theme():
    current_theme = session.get("theme")
    if current_theme == "dark":
        session["theme"] = "light"

    else:
        session["theme"] = "dark"

    return redirect(request.args.get("current_page"))

movie_library/templates/email_confirmation.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Confirm Your Email Address</title>
</head>
<body>
    <p>Hello {{ user_name }},</p>
    <br>
    <p>Thank you for registering on our website! Please click the button below to confirm your email address and complete your registration:</p>
    <p><a href="{{ confirmation_url }}"><button style="background-color: #008CBA; color: white; padding: 12px 24px; border: none; border-radius: 4px; cursor: pointer;">Confirm Email Address</button></a></p>
    <p>If the button above does not work, please copy and paste the following URL into your browser:</p>
    <p>{{ confirmation_url }}</p>
    <br>
    <img src="https://images.unsplash.com/photo-1542204165-65bf26472b9b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80"
         style="max-width: 50%; max-height: 50%; display: block;" alt="Movies Mail">
    <hr>
    <p style="font-size: 0.8em; color: grey;">This email was sent by Movies Watchlist Team. Please do not reply to this email.</p>

</body>
</html>

movie_library/templates/index.html
{% extends "layout.html" %}

{% block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/movies.css') }}" />
{% endblock %}

{% block main_content %}

    {%- if movies_data %}
        <table class="table">
            <colgroup>
                <col style="width: 60%">
                <col style="width: 25%">
                <col style="width: 15%">
            </colgroup>
            <thead>
                <tr class="table__header">
                    <th class="table__cell table__cell--header">Title</th>
                    <th class="table__cell table__cell--header">Release Date</th>
                    <th class="table__cell table__cell--header"></th>
                </tr>
            </thead>
            <tbody>
                {% for movie in movies_data %}
                    <tr>
                        <td class="table__cell">
                            <p class="table__movieTitle">{{ movie.title }}</p>
                            <p class="table__movieDirector">By {{ movie.director }}</p>
                        </td>
                        <td class="table__cell">{{ movie.year }}</td>
                        <td class="table__cell"><a href="{{ url_for('pages.movie', _id=movie._id) }}" class="table__link">View</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        
    {% else %}
        <p class="table__empty">You haven't added any movies yet. <a href="{{ url_for('pages.add_movie') }}" class="link">Add one!</a></p>
    {% endif %}

    <a href="{{ url_for('pages.add_movie') }}" class="button button--add">
        <span>+</span>
    </a>

{% endblock %}

movie_library/templates/layout.html
{% from "macros/nav.html" import header %}
{% from "macros/footer.html" import footer %}

<!DOCTYPE html>
<html lang="en" class="{{ 'dark-mode' if session.get('theme') == 'dark' }}">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>{{ title | default('Movie Watchlist') }}</title>
        <link href="https://fonts.googleapis.com/css?family=Public+Sans:400,600&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/reset.css') }}" />
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />


        {% block head_content %} {% endblock %}
    </head>
    
    <body>
        {{ header(session.get("email"), session.get("theme"), session.get("name")) }}

        <main class="main">
            {% block main_content %} {% endblock %}
        </main>



        {{ footer(year) }}
        <!-- Custom scripts for this template -->

    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    </body>
</html>

movie_library/templates/login.html
{% from "macros/fields.html" import render_text_field %}

{% extends "layout.html" %}

{%- block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %} 

{% block main_content %}

    <form name="login" method="post" novalidate class="form">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {%- for category, message in messages %}
                <span class="form__flash form__flash--{{category}}"> {{ message }}</span>
            {% endfor %}
        {% endwith %}

        <div class="form__container">
            {{ form.hidden_tag() }}
    
            {{ render_text_field(form.email) }}
            {{ render_text_field(form.password) }}
    
            <span class="form__small">
                Don't have an account? <a href="{{ url_for('pages.register') }}" class="form__link">Register here</a>.
            </span>
    
            <div>
                {{ form.submit(class_="button button--form") }}
            </div>
        </div>
    </form>

{% endblock %}

movie_library/templates/movie_details.html
{% from "macros/svgs.html" import star, pencil %}

{% extends "layout.html" %}

{%- block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/movie_details.css') }}" />
{% endblock %}

{% block main_content %}
<div class="container">
    <header class="movie__header">
        <div class="header__row">
            <div class="movie__name">
                <h1>{{ movie.title }}</h1>
                <div class="movie__rating">
                    {% for i in range(5) %}
                        <a class="rating__link" href="{{ url_for('pages.rate_movie', _id=movie._id, rating=i+1) }}">
                            {{ star("star " + ("star--filled" if movie.rating > i else "")) }}
                        </a>
                    {% endfor %}
                </div>
            </div>
            <div class="movie__watched">
                {% if movie.last_watched %}
                    <p>
                        Last watched: <a href="{{ url_for('pages.watch_today', _id=movie._id) }}" class="watched__link">
                            <time datetime="{{ movie.last_watched }}">{{movie.last_watched.strftime("%d %b %Y")}}</time>
                        </a>
                    </p>
                {% else %}
                    <p><a href="{{ url_for('pages.watch_today', _id=movie._id) }}" class="watched__link">Not watched yet</a></p>
                {% endif %}
                <a class="movie__edit" href="{{ url_for('pages.edit_movie', _id=movie._id) }}">Edit {{ pencil("pencil") }}</a>
            </div>
        </div>
        <div class="header__row">
            <ul class="movie__tags">
            {% for tag in movie.tags %}
                <li class="movie__tag">{{ tag }}</li>
            {% endfor %}
            </ul>
        </div>
    </header>
    {% if movie.video_link %}
    <iframe
        class="movie__video"
        src="{{ movie.video_link }}"
        title="YouTube video player"
        frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen>
    </iframe>
    {% endif %}

    {% if movie.description %}
        <p class="movie__description">{{ movie.description }}</p>
    {% else %}
        <p class="movie__description">No description yet. <a class="link" href="{{ url_for('pages.edit_movie', _id=movie._id) }}">Add one?</a></p>
    {% endif %}
    
    <div class="movie__meta">
        {% if movie.cast %}
            <div class="movie__casting">
                <h2>Casting</h2>
                <ul class="list">
                {% for actor in movie.cast %}
                    <li class="list__item">{{ actor }}</li>
                {% endfor %}
                </ul>
            </div>
        {% endif %}
        {% if movie.series | length %}
            <div class="movie__series">
                <h2>Series</h2>
                <ul class="list">
                {% for movie_in_series in movie.series %}
                    <li class="list__item">{{ movie_in_series }}</li>
                {% endfor %}
                </ul>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}

movie_library/templates/movie_form.html
{% from "macros/fields.html" import render_text_field, render_area_field %}

{% extends "layout.html" %}

{%- block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %}

{% block main_content %}

    <form name="add_movie" method="post" novalidate class="form">
        <div class="form__container">
            {{ form.hidden_tag() }}
            {{ render_text_field(form.title) }}
            {{ render_text_field(form.director) }}
            {{ render_text_field(form.year) }}

            {{ render_area_field(form.cast) }}
            {{ render_area_field(form.series) }}
            {{ render_area_field(form.tags) }}

            {{ render_area_field(form.description) }}
            {{ render_text_field(form.video_link) }}
    
            <div>
                {{ form.submit(class_="button button--form") }}
            </div>
        </div>
    </form>

{% endblock %}

movie_library/templates/new_movie.html
{% from "macros/fields.html" import render_text_field %}
{% extends 'layout.html' %}

{%- block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %}



{% block main_content %}


<form name="add_movie" method="post" novalidate class="form" id="new-movie-form">
    <div class="form__container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">


                {{ form.hidden_tag() }}
                {{ render_text_field(form.title) }}
                {{ render_text_field(form.director) }}
                {{ render_text_field(form.year) }}

                <div>
                    {{ form.submit(class_="button button--form", id="add-movie-button") }}
                </div>
            </div>
        </div>
    </div>
</form>


<br>


{% endblock %}

movie_library/templates/register.html
{% from "macros/fields.html" import render_text_field %}

{% extends "layout.html" %} 

{%- block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %} 

{% block main_content %}

    <form name="register" method="post" novalidate class="form">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {%- for category, message in messages %}
                <span class="form__flash form__flash--{{category}}"> {{ message }}</span>
            {% endfor %}
        {% endwith %}

        <div class="form__container">
            {{ form.hidden_tag() }}
            {{ render_text_field(form.name) }}
            {{ render_text_field(form.email) }}
            {{ render_text_field(form.password) }}
            {{ render_text_field(form.confirm_password) }}
    
            <span class="form__small">
                Already have an account? <a href="{{ url_for('pages.login') }}" class="form__link">Log in here</a>.
            </span>

            <div>
                {{ form.submit(class_="button button--form") }}
            </div>
            <br>

            <div>
                {{ render_text_field(form.recaptcha)}}
            </div>

        </div>
    </form>

{% endblock %}